export type Provider = "openai" | "anthropic" | "google";
export type Plan = "free" | "connect" | "pro";

export interface Room {
  id: string;
  name: string;
  createdAt: string;
  lastMessage?: string;
  lastMessageAt?: string;
  lastRunStatus?: RunStatus;
  archived?: boolean;
  archivedAt?: string;
}

export interface Message {
  id: string;
  roomId: string;
  /** "summary" = round summary generated by the moderator */
  role: "user" | "assistant" | "summary";
  agentId?: AgentId;
  /** Which debate side (A = Proposal, B = Review, C = Execution) */
  side?: "A" | "B" | "C";
  /** Debate round number (1 = Initial Stance, 2 = Challenge, 3 = Revision) */
  round?: number;
  content: string;
  createdAt: string;
  runId?: string;
}

export type AgentId = "gpt" | "claude" | "gemini";

export interface AgentInfo {
  id: AgentId;
  name: string;
  provider: Provider;
  color: string;
  initial: string;
}

/**
 * idle        = no run started
 * running     = rounds in progress
 * checkpoint  = rounds done, provisional conclusion generated — awaiting human decision
 * continued   = human chose to continue; additional rounds in progress
 * completed   = human chose to end here; conclusion finalized
 * error       = catastrophic failure
 */
export type RunStatus = "idle" | "running" | "checkpoint" | "continued" | "completed" | "error";

/**
 * idle        = no conclusion yet
 * loading     = generating in progress
 * provisional = checkpoint reached; provisional conclusion available (show end/continue buttons)
 * final       = human confirmed "end here"; conclusion is final
 * unresolved  = rounds done but AI could not generate even a provisional conclusion
 * error       = catastrophic failure
 */
export type ConclusionStatus = "idle" | "loading" | "provisional" | "final" | "unresolved" | "error";

export interface ConclusionData {
  summary: string;
  keyPoints: string[];
  generatedAt: string;
  /** Run ID that produced this conclusion */
  runId?: string;
  /** Sequential run number within the room (1-based) */
  runNumber?: number;
  /** True = provisional (checkpoint); false/undefined = final */
  isProvisional?: boolean;
  /** True = human explicitly confirmed "end here" */
  isFinal?: boolean;
}

export interface AgentSideConfig {
  side: "A" | "B" | "C";
  provider: Provider;
  model: string;
}

export type DefaultMode = "structured-debate" | "free-talk";

/** Writing tone for agent and moderator output */
export type WritingTone = "natural" | "professional" | "concise" | "casual";

/** Output format for the final conclusion */
export type ConclusionFormat = "paragraph" | "bullets";

/** Japanese formality level (affects JP-language outputs only) */
export type JpHardness = "soft" | "standard" | "formal";

export interface WritingStyle {
  tone:             WritingTone;
  conclusionFormat: ConclusionFormat;
  jpHardness:       JpHardness;
}

export type OutputDepth     = "rough" | "compare" | "concrete";
export type ChallengeLevel  = "soft"  | "standard" | "strong";

/**
 * Prompt Mode — user-defined debate configuration.
 * When present, agents must compare multiple candidates against explicit axes.
 */
export interface PromptConfig {
  goal:            string;         // A: 議論の目的
  decisionTarget:  string;         // B: 最終的に決めたいこと
  comparisonAxes:  string[];       // C: 比較軸 (multi-select)
  constraints:     string;         // D: 制約条件
  priorities:      string;         // E: 優先順位
  outputDepth:     OutputDepth;    // F: 出力の粒度
  challengeLevel:  ChallengeLevel; // G: 反論の強さ
}

export interface Settings {
  openaiApiKey:    string;
  anthropicApiKey: string;
  googleApiKey:    string;
  sideA:           AgentSideConfig;
  sideB:           AgentSideConfig;
  sideC:           AgentSideConfig;
  defaultMode:     DefaultMode;
  agentCount:      2 | 3;
  writingStyle:    WritingStyle;
}
