export type Provider = "openai" | "anthropic" | "google";
export type Plan = "free" | "connect" | "pro";

export interface Room {
  id: string;
  name: string;
  createdAt: string;
  lastMessage?: string;
  lastMessageAt?: string;
  lastRunStatus?: RunStatus;
  archived?: boolean;
  archivedAt?: string;
}

export interface Message {
  id: string;
  roomId: string;
  /** "summary" = round summary generated by the moderator */
  role: "user" | "assistant" | "summary";
  agentId?: AgentId;
  /** Which debate side (A = Proposal, B = Review, C = Execution) */
  side?: "A" | "B" | "C";
  /** Debate round number (1 = Initial Stance, 2 = Challenge, 3 = Revision) */
  round?: number;
  content: string;
  createdAt: string;
  runId?: string;
}

export type AgentId = "gpt" | "claude" | "gemini";

export interface AgentInfo {
  id: AgentId;
  name: string;
  provider: Provider;
  color: string;
  initial: string;
}

export type RunStatus = "idle" | "running" | "completed" | "error";

export interface ConclusionData {
  summary: string;
  keyPoints: string[];
  generatedAt: string;
  /** Run ID that produced this conclusion */
  runId?: string;
  /** Sequential run number within the room (1-based) */
  runNumber?: number;
}

export interface AgentSideConfig {
  side: "A" | "B" | "C";
  provider: Provider;
  model: string;
}

export type DefaultMode = "structured-debate" | "free-talk";

export interface Settings {
  openaiApiKey: string;
  anthropicApiKey: string;
  googleApiKey: string;
  sideA: AgentSideConfig;
  sideB: AgentSideConfig;
  sideC: AgentSideConfig;
  defaultMode: DefaultMode;
  agentCount: 2 | 3;
}
