export type Provider   = "openai" | "anthropic" | "google";
export type Plan       = "free" | "connect" | "pro";
export type AccessType = "normal" | "tester" | "early_access" | "special";
export type UserRole   = "user" | "admin";

export interface UserProfile {
  role:                UserRole;
  plan:                Plan;
  accessType:          AccessType;
  isUnlimitedUser:     boolean;
  dailyRunLimit:       number | null;
  monthlyRunLimit:     number | null;
  continuationLimit:   number | null;
  inviteCodeAppliedAt: string | null;
}

export interface Room {
  id: string;
  name: string;
  createdAt: string;
  lastMessage?: string;
  lastMessageAt?: string;
  lastRunStatus?: RunStatus;
  archived?: boolean;
  archivedAt?: string;
}

export interface Message {
  id: string;
  roomId: string;
  /** "summary" = round summary generated by the moderator */
  role: "user" | "assistant" | "summary";
  agentId?: AgentId;
  /** Which debate side (A = Proposal, B = Review, C = Execution) */
  side?: "A" | "B" | "C";
  /** Debate round number (1 = Initial Stance, 2 = Challenge, 3 = Revision) */
  round?: number;
  content: string;
  createdAt: string;
  runId?: string;
}

export type AgentId = "builder" | "breaker" | "operator";

export interface AgentInfo {
  id: AgentId;
  name: string;
  provider: Provider;
  color: string;
  initial: string;
}

/**
 * idle        = no run started
 * running     = rounds in progress
 * checkpoint  = rounds done, provisional conclusion generated — awaiting human decision
 * continued   = human chose to continue; additional rounds in progress
 * completed   = human chose to end here; conclusion finalized
 * error       = catastrophic failure
 */
export type RunStatus = "idle" | "running" | "checkpoint" | "continued" | "completed" | "error";

/**
 * idle        = no conclusion yet
 * loading     = generating in progress
 * provisional = checkpoint reached; provisional conclusion available (show end/continue buttons)
 * final       = human confirmed "end here"; conclusion is final
 * unresolved  = rounds done but AI could not generate even a provisional conclusion
 * error       = catastrophic failure
 */
export type ConclusionStatus = "idle" | "loading" | "provisional" | "final" | "unresolved" | "error";

export interface ConclusionData {
  summary: string;
  keyPoints: string[];
  generatedAt: string;
  /** Run ID that produced this conclusion */
  runId?: string;
  /** Sequential run number within the room (1-based) */
  runNumber?: number;
  /** True = provisional (checkpoint); false/undefined = final */
  isProvisional?: boolean;
  /** True = human explicitly confirmed "end here" */
  isFinal?: boolean;
}

export interface AgentSideConfig {
  side: "A" | "B" | "C";
  provider: Provider;
  model: string;
}

export type DefaultMode = "structured-debate" | "free-talk";

/** Writing tone for agent and moderator output */
export type WritingTone = "natural" | "professional" | "concise" | "casual";

/** Output format for the final conclusion */
export type ConclusionFormat = "paragraph" | "bullets";

/** Japanese formality level (affects JP-language outputs only) */
export type JpHardness = "soft" | "standard" | "formal";

export interface WritingStyle {
  tone:             WritingTone;
  conclusionFormat: ConclusionFormat;
  jpHardness:       JpHardness;
}

export type OutputDepth     = "rough" | "compare" | "concrete";
export type ChallengeLevel  = "soft"  | "standard" | "strong";

/** A single comparison axis with a user-assigned weight */
export interface ComparisonAxis {
  name:   string;
  weight: "high" | "medium" | "low";
}

/**
 * Prompt Mode — user-defined debate configuration.
 * When present, agents must compare multiple candidates against explicit axes.
 */
export interface PromptConfig {
  goal:            string;            // 議論の目的 (legacy / free-form goal)
  decisionTarget:  string;            // 最終的に決めたいこと
  comparisonAxes:  ComparisonAxis[];  // 比較軸 (with weights)
  constraints:     string;            // 前提・制約
  priorities:      string;            // 優先順位 (legacy)
  outputDepth:     OutputDepth;       // 出力粒度
  challengeLevel:  ChallengeLevel;    // 反論の強さ
  templateId?:     string;            // selected template id (optional)
}

export interface Settings {
  openaiApiKey: string;
  sideA:        AgentSideConfig;
  sideB:        AgentSideConfig;
  sideC:        AgentSideConfig;
  defaultMode:  DefaultMode;
  agentCount:   2 | 3;
  writingStyle: WritingStyle;
}
