import { useState } from "react";
import { ChevronDownIcon, ChevronUpIcon, SparklesIcon } from "lucide-react";

interface Conclusion {
  summary: string;
  keyPoints: string[];
  generatedAt: string;
}

interface Props {
  runCount: number;
  conclusion: Conclusion | null;
}

function formatTime(iso: string): string {
  return new Date(iso).toLocaleTimeString([], { hour: "2-digit", minute: "2-digit" });
}

export default function ConclusionCard({ runCount, conclusion }: Props) {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <div className="mx-4 mb-2">
      <button
        onClick={() => setIsOpen((p) => !p)}
        className={`w-full flex items-center justify-between px-4 py-2.5 text-sm font-medium border transition-colors ${
          isOpen
            ? "border-b-0 rounded-t-lg bg-card border-border"
            : "rounded-lg bg-card border-border hover:bg-accent/40"
        }`}
      >
        <div className="flex items-center gap-1.5 text-foreground">
          <SparklesIcon size={13} className="text-muted-foreground" />
          <span>Conclusion</span>
        </div>
        <div className="flex items-center gap-1.5 text-muted-foreground">
          <span className="text-xs">
            {runCount} {runCount === 1 ? "run" : "runs"}
          </span>
          {isOpen ? <ChevronDownIcon size={14} /> : <ChevronUpIcon size={14} />}
        </div>
      </button>

      {isOpen && (
        <div className="border border-t-0 border-border rounded-b-lg bg-card px-4 pt-3 pb-4">
          {conclusion ? (
            <>
              <p className="text-sm text-foreground leading-relaxed">{conclusion.summary}</p>
              <ul className="mt-3 space-y-1.5">
                {conclusion.keyPoints.map((pt, i) => (
                  <li key={i} className="flex items-start gap-2 text-xs text-muted-foreground">
                    <span className="mt-1.5 w-1 h-1 rounded-full bg-primary shrink-0" />
                    {pt}
                  </li>
                ))}
              </ul>
              <p className="mt-3 text-xs text-muted-foreground/70">
                Generated at {formatTime(conclusion.generatedAt)} ·{" "}
                <span className="italic">Placeholder — will be generated by agents in production</span>
              </p>
            </>
          ) : (
            <p className="text-sm text-muted-foreground italic">
              Conclusion will appear here after the discussion runs.
            </p>
          )}
        </div>
      )}
    </div>
  );
}
